# render.yaml - Configuración corregida sin errores
services:
  # Servicio web principal
  - type: web
    name: yachay-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend/
    plan: starter
    healthCheckPath: /api/detection/status/
    envVars:
      - key: RENDER
        value: "true"
      - key: DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost"
      - key: DATABASE_URL
        fromDatabase:
          name: yachay-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: yachay-redis
          type: redis
          property: connectionString

  # Servicio Redis
  - type: redis
    name: yachay-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all connections

# Base de datos PostgreSQL
databases:
  - name: yachay-postgres
    plan: starter
    databaseName: yachay
    user: yachay_user