# Generated by Django 4.2.9 on 2024-12-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_label', models.CharField(db_index=True, max_length=100, unique=True)),
                ('spanish', models.CharField(max_length=100)),
                ('quechua', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Traducción de Objeto',
                'verbose_name_plural': 'Traducciones de Objetos',
                'ordering': ['english_label'],
                'indexes': [models.Index(fields=['spanish'], name='translation_spanish_a75a59_idx'), models.Index(fields=['quechua'], name='translation_quechua_998b3e_idx')],
            },
        ),
    ]
