# Generated by Django 5.2 on 2025-05-10 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('vocabulary', 'Vocabulario'), ('mastery', 'Dominio'), ('streak', 'Constancia'), ('exploration', 'Exploración')], max_length=20)),
                ('requirement_value', models.IntegerField()),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('detection', 'Detección'), ('practice', 'Práctica')], default='detection', max_length=20)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('word_learned', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_label', models.CharField(db_index=True, max_length=100, unique=True)),
                ('spanish', models.CharField(max_length=100)),
                ('quechua', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Traducción de Objeto',
                'verbose_name_plural': 'Traducciones de Objetos',
                'ordering': ['english_label'],
                'indexes': [models.Index(fields=['spanish'], name='translation_spanish_a75a59_idx'), models.Index(fields=['quechua'], name='translation_quechua_998b3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('multiple_choice', 'Selección múltiple'), ('fill_blanks', 'Completar espacios'), ('matching', 'Relacionar'), ('pronunciation', 'Pronunciación'), ('anagram', 'Ordenar letras')], max_length=20)),
                ('category', models.CharField(choices=[('vocabulary', 'Vocabulario'), ('pronunciation', 'Pronunciación'), ('grammar', 'Gramática'), ('detection', 'Detección'), ('phrases', 'Frases'), ('memory', 'Memoria')], default='vocabulary', max_length=20)),
                ('difficulty', models.IntegerField(default=1)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('distractors', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.objecttranslation')),
            ],
        ),
        migrations.CreateModel(
            name='PronunciationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='pronunciation_records/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approval_comment', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pronunciations', to=settings.AUTH_USER_MODEL)),
                ('object_translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.objecttranslation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_words', models.IntegerField(default=0)),
                ('mastered_words', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('native_speaker', models.BooleanField(default=False)),
                ('preferred_dialect', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('words_detected', models.IntegerField(default=0)),
                ('words_practiced', models.IntegerField(default=0)),
                ('words_mastered', models.IntegerField(default=0)),
                ('detection_goal', models.IntegerField(default=3)),
                ('practice_goal', models.IntegerField(default=5)),
                ('mastery_goal', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('correct', models.BooleanField(default=False)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='UserVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_label', models.CharField(max_length=100)),
                ('spanish_word', models.CharField(max_length=100)),
                ('quechua_word', models.CharField(max_length=100)),
                ('mastery_level', models.IntegerField(default=1)),
                ('exercises_completed', models.IntegerField(default=0)),
                ('exercises_correct', models.IntegerField(default=0)),
                ('times_detected', models.IntegerField(default=1)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('mastered_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Vocabulary',
                'verbose_name_plural': 'User Vocabularies',
                'unique_together': {('user', 'quechua_word')},
            },
        ),
    ]
