# Generated by Django 5.2 on 2025-05-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoal',
            name='date',
            field=models.DateField(),
        ),
    ]
