# Generated by Django 4.2.9 on 2025-03-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_achievement_exercise_userprofile_pronunciationrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
