# Generated by Django 5.2 on 2025-05-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_alter_dailygoal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocabulary',
            name='consecutive_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='mode',
            field=models.CharField(choices=[('detection', 'Detección'), ('practice', 'Práctica'), ('system', 'Sistema')], default='detection', max_length=20),
        ),
    ]
