# Generated by Django 4.2.9 on 2025-03-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_exercise_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Selección múltiple'), ('fill_blanks', 'Completar espacios'), ('matching', 'Relacionar'), ('pronunciation', 'Pronunciación'), ('anagram', 'Ordenar letras')], max_length=20),
        ),
    ]
