# Generated by Django 5.2 on 2025-05-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_uservocabulary_abandoned_exercises_exercisesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocabulary',
            name='previous_mastery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
