# Generated by Django 5.2 on 2025-04-25 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_alter_exercise_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_days', models.IntegerField(unique=True)),
                ('reward_name', models.CharField(max_length=100)),
                ('reward_description', models.TextField()),
                ('bonus_points', models.IntegerField(default=0)),
                ('icon', models.CharField(default='star', max_length=50)),
            ],
            options={
                'verbose_name': 'Recompensa por Racha',
                'verbose_name_plural': 'Recompensas por Racha',
                'ordering': ['streak_days'],
            },
        ),
        migrations.AddField(
            model_name='activitylog',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='mode',
            field=models.CharField(choices=[('detection', 'Detección'), ('practice', 'Práctica')], default='detection', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('vocabulary', 'Vocabulario'), ('pronunciation', 'Pronunciación'), ('grammar', 'Gramática'), ('detection', 'Detección'), ('phrases', 'Frases'), ('memory', 'Memoria')], default='vocabulary', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_practice_time',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('exercises_completed', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Práctica',
                'verbose_name_plural': 'Sesiones de Práctica',
            },
        ),
        migrations.CreateModel(
            name='ProgressCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vocabulary', 'Vocabulario'), ('pronunciation', 'Pronunciación'), ('grammar', 'Gramática'), ('detection', 'Detección'), ('phrases', 'Frases'), ('memory', 'Memoria')], max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('exercises_completed', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso por Categoría',
                'verbose_name_plural': 'Progresos por Categoría',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
